import json
from datetime import datetime
import argparse
import sys 
import requests
import smtplib
from email.mime.text import MIMEText

# Set up argument parsing
parser = argparse.ArgumentParser()
parser.add_argument("diff_file", help="Enter the path to the diff file generated by diff_reports.py")
parser.add_argument("config", help="Enter the path to the config file for smtplib")
args = parser.parse_args()

# Initialize timestamps and variables
date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
today = datetime.now().strftime("%Y-%m-%d")
diff_file = args.diff_file 
config_file = args.config
high_findings = []
high_findings_exists = False

# Load diff file and extract new HIGH findings
if diff_file.endswith('.json'):
    with open(diff_file, "r") as f:
        data = json.load(f)
    for finding in data.get("New findings", []):
       if finding[0]["Severity"] == "HIGH":
         high_findings.append(finding)
         high_findings_exists = True
else:
    print("Please enter a JSON file")
    sys.exit(1)

# Load email configuration
if config_file.endswith('.json'):
    with open(config_file, "r") as f:
        config_file = json.load(f)
else:
    print("Please enter a JSON file")
    sys.exit(1)    

# Function to format and send the email
def send_email_and_discord_msg(high_findings, config_file):
    body = "🚨New HIGH severity findings :\n\n"
    body += f"- date : {date}\n"
    body += f"- New HIGH findings: {len(high_findings)}\n\n"
    
    for finding in high_findings:
        affected = ''
        for k, v in finding[0].items():
            if k.startswith('Affected'):
                for item in v:
                    for ak, av in item.items():
                        affected += f" {ak} : {av} "
                    affected += " | "
        body += f"[HIGH] {finding[0]['Check']} : {affected}\n\n"
        
    body += f"\n\n\nView full report: /var/reports/report_{today}.html"
    
    # Set up the email message
    msg = MIMEText(body)
    msg["Subject"] = "🚨 Security Alert"
    msg["From"] = config_file["email_from"]
    msg["To"] = config_file["email_to"]

    
    try:
        # Connect to SMTP server and send email
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
            smtp.login(config_file["email_from"], config_file["email_password"])
            smtp.send_message(msg)
            print("[✓] Email envoyé")
        # send discord message 
        alert = {
            "content": body
        }
        web_hook = config_file["discord_webhook"]
        requests.post(web_hook, json=alert)
        print("[✓] Discord message envoyé")
    except Exception as e:
        print(f"[!] Alert non envoyé : {e}")
    
    

# Trigger the email alert if there are any high severity findings
if high_findings_exists:
    send_email_and_discord_msg(high_findings, config_file)
else:
    print("[✓] Aucune nouvelle faille HIGH détectée.")
